version: "3.3"

services:
  web:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: "backend"
    restart: unless-stopped
    command: bash -c "
      python application.py
      "
    ports:
      - "8080:8080"
    tty: true